language: c
compiler: gcc
os: osx

script:
  - travis_retry git clone -v https://github.com/Snaipe/BoxFort.git && cd BoxFort
  - git checkout 38135f9be719270eeb04dbb77d335d13d91e03c1
  - mkdir build && cd build
  - cmake .. && make
  - ./sample/nested.c.bin
